# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a2cdc169cc6baee419c8f7f4107fcb121df53866a987d9c793dc0071da56196a641b59c05c25f59577017c8d9bfd9694cd9466176c7e8da0ccf9719f1926519

test:
  secret_key_base: a367d41e7c78c0c98d84eb6fbfb3d7520df2dc806c0ca48fdb099a948bb49a966a31d6281bdf99f5298bebe9db2d3bbeb3e65a2dbdac18cc2a580edf15710157

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
